project: default
source:
  repoURL: https://github.com/brown-a2/jellyfin
  path: ./
  targetRevision: main
destination:
  server: https://kubernetes.default.svc
  namespace: jellyfin
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
