apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-ingress-cluster-role
rules:
  # Permissions for core resources like secrets, configmaps, services, and nodes
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
      - services
      - nodes
    verbs:
      - get
      - list
      - watch
  # Permissions for endpoint slices
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  # Permissions for leader leases
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
  # Permissions for ingress classes
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingressclasses
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-ingress-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: nginx-ingress-serviceaccount
    namespace: ingress-nginx
roleRef:
  kind: ClusterRole
  name: nginx-ingress-cluster-role
  apiGroup: rbac.authorization.k8s.io
